### ISSUE TITLE
Disable demo mode

### ISSUE THREAD

**Issue by Denqe** [logdyhq/logdy-core#64]
Hello! After setting up logdy through my domain, which has the exampledemo subdomain, the application opens in demo mode, how can I switch to using the normal mode, other than changing the subdomain? I use nginx proxying.

**Comment by PeterOsinski** [comment]
Hi @Denqe indeed its a problem with the UI that picksup the `demo` keyword in the `document.location.host`. I'll deploy a fix and let you know.

**Comment by PeterOsinski** [comment]
@Denqe it has been fixed in the latest release, you can update Logdy now

**Comment by Denqe** [comment]
@PeterOsinski Thanks for the help, but after downloading the latest version 0.13.1 the problem continues to reproduce. I'm using subdomains: demotest. and exampledemo. Is this actually added to the latest release?

**Comment by PeterOsinski** [comment]
@Denqe what does `logdy --version` output? Did you clear the cache of he browser? Maybe the frontend scripts gets cached?

**Comment by Denqe** [comment]
@PeterOsinski the command output shows: logdy version 0.13.1 , I tried many methods, clearing the cache, another PC, incognito browser mode, reinstalling on another host - I still see demo mode, maybe you have the opportunity to make sure that this does not work...

**Comment by PeterOsinski** [comment]
Hi I just released another version, I didn't change much but I added a version indicator in the UI to make sure the changes are really in the UI, could you update your version (not through homebrew as the changes are not there yet) and let me know what version do you see?
![image](https://github.com/user-attachments/assets/5718ae1d-075a-41ef-9542-cde582035bda)

**Comment by Denqe** [comment]
Hello!
![image](https://github.com/user-attachments/assets/c3d3397b-f137-4651-9e8d-2dfd4ba1793e)
inside the server I see - `logdy version 0.13.2`
I downloaded the version from here `wget https://github.com/logdyhq/logdy-core/releases/download/v0.13.2/logdy_linux_amd64`

**Comment by Denqe** [comment]
Hello! Thank you, now displays correctly. But there is still no version indicator in the web console.
![image](https://github.com/user-attachments/assets/d8539a15-427f-4a9f-9d18-b55611bff534)

**Comment by PeterOsinski** [comment]
oh by web console I meant the one you open in Chrome for example.
<img width="993" alt="Zrzut ekranu 2024-11-26 o 22 20 26" src="https://github.com/user-attachments/assets/c64a46bf-fc05-48e6-b77d-aab9b326294e">

I'm glad all is working fine now! Closing 🤝
